### ISSUE TITLE
Bug in GetReportData()?

### ISSUE THREAD

**Issue by hack-r** [Tatvic/RGoogleAnalytics#18]
I was using RGoogleAnalytics without any trouble in June and July of this year. I went back to re-run the code Friday and today and now all queries using GetReportData() return this error:

    Error in ParseDataFeedJSON(GA.Data) : 
      code : 401 Reason : Invalid Credentials

After verifying that my credentials and table ID are correct, I found an old thread started in 2012 on Google Groups which indicated that this happened back then due to a change in the API (https://code.google.com/p/r-google-analytics/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&groupby=&sort=&id=4) . 

Is that the case now?

I have tried both the CRAN and Github versions and gotten the same results.

Update -- I also tried creating a new client ID and secret to authenticate and got the following result:

````
> Auth(client.id, client.secret)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
<Token>
<oauth_endpoint>
 authorize: https://accounts.google.com/o/oauth2/auth
 access:    https://accounts.google.com/o/oauth2/token
 validate:  https://www.googleapis.com/oauth2/v1/tokeninfo
 revoke:    https://accounts.google.com/o/oauth2/revoke
<oauth_app> google
  key:    128468508459-0ttjdmr4fff01feqq2b3ferllp1iupc1.apps.googleusercontent.com
  secret: <hidden>
<credentials> error
---
> token         <- Auth(client.id,client.secret)
> save(token, file="token_file")
> # saveRDS(token, file = "token.rds")
> query.list <- Init(start.date = "2014-08-01",
+                    end.date = "2015-08-13",
+                    dimensions = c("ga:source", "ga:medium"),
+                    metrics = "ga:sessions,ga:transactions",
+                    max.results = 10000,
+                    sort = "-ga:transactions",
+                    table.id = "ga:100864528")
> 
> # Create the Query Builder object so that the query parameters are validated
> ga.query <- QueryBuilder(query.list)
> 
> # Extract the data and store it in a data-frame
> ga.data <- GetReportData(ga.query, token = token)
Error in ParseDataFeedJSON(GA.Data) : code : 401 Reason : Login Required
````

**Comment by hack-r** [comment]
I think it was something to do with changing the password on my Google Account. I've got it working again.

**Comment by nbyloff** [comment]
I am getting the same issue. Is this project abandoned?

**Comment by DavidArenburg** [comment]
This is probably should be reopened. This is a very annoying bug that happens all the time and it makes it impossible to embed this inside this inside a function instead of manually rerunning this

**Comment by DavidArenburg** [comment]
Either way, I think I found a hack to solve this. Try running `invisible(GetProfiles(token))` right after defining the `token`. It seem to allow future operations without errors.

**Comment by d8aninja** [comment]
I too am having this issue suddenly...

**Comment by withetu** [comment]
@DavidArenburg, thanks. Its worked for me.
