### ISSUE TITLE
filtering ga:landingPagePath with character '&'

### ISSUE THREAD

**Issue by zhaoyizhaoyi** [Tatvic/RGoogleAnalytics#19]
Often I have to filter landing pages with character '&', like '/index.html&channel=1'. In RGoogleAnalytics, the right way to do this seems to be: filters="ga:landingPagePath=~^/index\.html&channel=1'(I want to filter all landing pages starting with '/index.html&channel=1').
However, it turns out that this filtering condition returns some really weird results, which are obviously not what I want. And by checking for some time, I think the problem hinges on character '&'. When I replace '&' with '.', it makes sense(though it is not exactly what I desire). 
So anyone who knows what is the problem with character '&' in regular expression here? As I know, it doesn't work when I try to replace '&' with '\&'.

**Comment by jdeboer** [comment]
Perhaps the & character is not being URL encoded as it should?

**Comment by zhaoyizhaoyi** [comment]
jdeboer, thanks a lot! Finally it seems I should use '%26' instead of '&' in the regular expression. Still I do not know reason why the regular expression cannot recognize '&', but it's OK to use '%26'. I try to search this in google, but no satisfactory answers have been found.
