### ISSUE TITLE
Unused Arguments

### ISSUE THREAD

**Issue by jens86** [Tatvic/RGoogleAnalytics#20]
Hi I'm recieving an error when creating the query list.
Do you know why/how to avoid it?

KR,
Jens

query.list <- Init(start.date = "2015-10-28",
+                    end.date = "2015-11-04",
+                    dimensions = "ga:date,ga:pagePath,ga:hour,ga:medium",
+                    metrics = "ga:sessions,ga:pageviews",
+                    max.results = 10000,
+                    sort = "-ga:date",
+                    table.id = "ga:73742508")
Error in Init(start.date = "2015-10-28", end.date = "2015-11-04", dimensions = "ga:date,ga:pagePath,ga:hour,ga:medium",  : 
  unused arguments (max.results = 10000, sort = "-ga:date", table.id = "ga:73742508")

**Comment by dikesh** [comment]
Can you please provide us the entire code?
