### ISSUE TITLE
Dimensions param is not nullable in Init

### ISSUE THREAD

**Issue by ashleylester** [Tatvic/RGoogleAnalytics#36]
The Init function does not work when it is passed a parameter `dimensions=NULL`, and it does not work when dimensions are unspecified (i.e. the default argument is used). However on page 5 of the CRAN documentation it states dimensions are optional in the Init function.

The call fails with `Error in if (!grepl("ga:` (...) `argument is of length zero`

**Comment by dikesh** [comment]
Can you show what you are passing to `Init` function?
