### ISSUE TITLE
Filtering with hyphenated values

### ISSUE THREAD

**Issue by ashleylester** [Tatvic/RGoogleAnalytics#37]
I can't figure out how to bring back data with hyphenated values and have tried enough configurations that makes me think it might be a bug.

For example:

    "ga:pagePath%3D~blue-cars"

I want to match all paths containing the substring blue-cars. The regex is greedy so I don't need anchors.

The above does not work because a hyphen is a something (to) something in regex. E.g. 1-9.

If I do

    "ga:pagePath%3D~blue\-cars"

R will escape the hyphen because there is a backslash in the string, so this is not correct syntactically.

If I do 

    "ga:pagePath%3D~blue\\-cars"

This works but it does not retrieve any data from GA. I know there is data for these page tracks because I can see it in the frontend. I can successfully retrieve data if I just use

    "ga:pagePath%3D~cars"

This works as expected.

**Comment by dikesh** [comment]
Since you want to match all paths containing the substring blue-cars, have you tried `ga:pagePath%3D@blue-cars` ?

**Comment by dikesh** [comment]
`ga:pagePath=~blue-cars` should also work. May be just use `=` instead of `%3D`

**Comment by ashleylester** [comment]
Both of those work but again no data from GA is bough back. I can see the paths on the front-end, so I don't quite understand it. I also checked to make sure that they aren't em-dashes or some other weird character. If I re-run the query without the hyphen and instead look at another part of the page path, it works.

One interesting thing I noticed is that it doesn't work with underscores either. Does this give a clue?

**Comment by dikesh** [comment]
Same regex is working on my system.
Have you install using `devtools::install_github("Tatvic/RGoogleAnalytics")` ? If not can you please do so?

**Comment by ashleylester** [comment]
Still the same unfortunately. 

However, since it appears to be working on your system, I'll clean my environment and do some testing on a minimal example.

**Comment by ashleylester** [comment]
Hey @dikesh 

This has been resolved - there is no bug here. It was due to a combination of inconsistent tagging and some package conflicts in my environment. I'm closing this. Thanks for your help and apologies for not noticing it before I filed the request.

**Comment by dikesh** [comment]
No worries @ashleylester .
What about issue#36. Is it resolved?
